name: Publish Any Commit
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm build

      - name: Publish
        run: npx pkg-pr-new publish
